- name: Build PXE environment
  hosts: localhost
  roles:
    - pxe-server

- name: Provision OS on machines
  hosts: metal
  gather_facts: false
  roles:
    - wol-wake

- name: Tear down PXE stack
  hosts: localhost
  gather_facts: false
  roles:
    - pxe-teardown