- name: Build PXE environment
  hosts: localhost
  roles:
    - pxe-server

- name: Provision OS on machines
  hosts: metal
  gather_facts: false
  roles:
    - wol-wake

- name: Clean up PXE environment
  hosts: localhost
  gather_facts: false
  roles:
    - pxe-cleanup

- name: Configure networking
  hosts: metal
  roles:
    - systemd-networkd