version: "3"

services:
  dhcp:
    build: ./dhcp
    volumes:
      - ./data/pxe-config/dhcpd.conf:/etc/dhcp/dhcpd.conf
    network_mode: host
  tftp:
    build: ./tftp
    network_mode: host
    volumes:
      - ./data/os/debian-installer/amd64/grub:/var/lib/tftpboot/debian-installer/amd64/grub
      - ./data/pxe-config/grub.cfg:/var/lib/tftpboot/debian-installer/amd64/grub/grub.cfg
      - ./data/os/debian-installer/amd64/grubx64.efi:/var/lib/tftpboot/grubx64.efi
      - ./data/os/debian-installer/amd64/initrd.gz:/var/lib/tftpboot/initrd.gz
      - ./data/os/debian-installer/amd64/linux:/var/lib/tftpboot/linux
      - ./data/preseed:/var/lib/tftpboot/preseed
